### PR TITLE
Major update v2

### LINKED ISSUE #2: Gatsby node ownership
As mentioned [here](https://github.com/d4rekanguok/gatsby-typescript/issues/4#issuecomment-587290120), Gatsby has an issue with a plugin modifying nodes that "it didn't create".  It seems to only apply when `gatsby-node` is found in the project root; it works fine when it is located in a sub directory.

Perhaps, because of this, in order to use a plugin like this, storing the configuration files in a sub-directory should be mandatory.  That could, potentially, raise compatibility concerns with various other 3rd party plugins, or any Gatsby process that requires the presence of these files in the project root.  My testing thus far hasn't exposed compatibility concerns like that yet, but I would wager a guess that they exist.

I'm not sure yet if there's a decent, and stable, fix for this.  Perhaps, in a scenario where a certain config file is required to be in the root, a "split" could be set up.  The bulk of the work could be done in Typescript, in a sub-directory, and a root copy/stub could be created for compatibility with whatever process needs it.  I really not a fan of having to maintain split configurations, though; that's definitely something I'm trying to avoid.

More investigation is required.

cc/ @d4rekanguok - _thought you might be interested in my findings on this particular subject_

### LINKED ISSUE #18: Unable to type already defined GraphQL types
First of all, I love the plugin, and thank you so much for building it! 😄 

I am using Kentico as the CMS for my application. The [@kentico/gatsby-source-kontent](https://github.com/Kentico/kontent-gatsby-packages/tree/master/packages/gatsby-source-kontent) package defines the GraphQL types. I try to leverage the [sourceNodes API](https://www.gatsbyjs.com/docs/node-apis/#sourceNodes) to create special typing:
```
export const sourceNodes = ({actions: {createTypes}}: SourceNodesArgs) => {
  createTypes(`
    type kontent_item_rich_text_element_link {
      element: Node! @link(from: "element___NODE")
    }
  `)
}
```
But, when I run a `gatsby develop`, I get this:
```
warn Plugin `gatsby-plugin-ts-config` tried to define the GraphQL type `kontent_item_rich_text_element_link`, which has already been defined by the plugin `@kentico/gatsby-source-kontent`.
```
My theory is that `@kentico/gatsby-source-kontent` defines the type and then `gatsby-plugin-ts-config` tries to redefine the type, so Gatsby throws the warning and doesn't allow the plugin to do so. As a result, my custom typing does not work. This may not even be an issue with this plugin but any direction is helpful! Perhaps there is a way to tell Gatsby to allow this?

I appreciate your time and intention with this plugin! Let me know if there is anything else I can provide to help explain the issue better. 😄

### LINKED ISSUE #20: When using yarn workspaces and gatsby-themes, there is an infinite loop on "open and validate gatsby-configs"
I have a workspace like so:

```json
//workspace package.json
{
  "workspaces": [
    "gatsby-theme-project-core",
    "gatsby-theme-project-uses-core",
    "my-site"
  ],
  "resolutions": {
    "gatsby-theme-project-core": "*",
    "gatsby-theme-project-using-core": "*"
  }
}
```
both `project-core` and `project-uses-core` have a `gatsby-config.js` of
```js
const tsconfig = require("gatsby-plugin-ts-config")

module.exports = tsconfig.generateConfig({
  configDir: ".gatsby",
  projectRoot: __dirname,
})
```
my-site does not use `gatsby-plugin-ts-config`, and uses a more normal `gatsby-config.js` of just requiring the two above. It's purpose is to only hold content.

And when I go to run `yarn workspace my-site run build` locally after a clean, I get an "open and validate gatsby-configs" that lasts forever.

### LINKED ISSUE #26: Gatsby plugin de-duplication issues
Gatsby uses a scoped require when resolving plugins (it resolves them from the context of a theme/plugin that provides them), and `gatsby-plugin-ts-config` proxies the default site's plugins, Gatsby is generally unable to resolve them.  Because of this, they are resolved to absolute paths before passing them back to Gatsby.

The issue with this is that it will break de-duplication.  For example, if the default site defines a plugin, say `gatsby-plugin-sharp` and a theme defines the same plugin, the default site's plugin metadata becomes
```
{
  resolve: '/absolute/path/to/node_modules/gatsby-plugin-sharp'
}
```
Meanwhile, the theme's plugin metadata will likely look like:
```
{
  resolve: 'gatsby-plugin-sharp'
}
// or
[
  'gatsby-plugin-sharp'
]
```

Gatsby's plugin de-duplication looks at the `resolve` and `options` properties on the plugin metadata.  If they are the same, they are de-duplicated.  Any plugins served via `gatsby-plugin-ts-config` _**will not match**_ plugins defined using just its name.

See #24 and https://github.com/gatsbyjs/gatsby/pull/28523

### LINKED ISSUE #27: The resolve prop override breaks some default Gatsby behavior
https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/218f88c6d895958c3ad7d7564ec4c7f26abbae26/src/gatsby/gatsby-config.ts#L102

I notice that I couln't override `gatsby-plugin-page-creator` with this plugin

The reason is, Gatsby will compare the resolve prop like here:

https://github.com/akshayymahajan/gatsby/blob/05d65363bcd2a37fc65ca619c62279cbd9ba62b2/packages/gatsby/src/bootstrap/load-plugins/load.js#L224

```js
        plugin.resolve === `gatsby-plugin-page-creator` &&
```

### LINKED ISSUE #29: Gatsby v3
Yesterday, Gatsby v3 got released. I've upgraded already two projects. They also use `gatsby-plugin-ts-config`. So far everything seems to work! Awesome 🥇

After some more testing I think the peer dependency should be updated and a new version released.

```
warn Plugin gatsby-plugin-ts-config is not compatible with your gatsby version 3.0.0 - It requires gatsby@~2.x.x
```

### PR DESCRIPTION
**Pull request by Js-Brecht**
This is the initial v2 rewrite, implementing the "Isolated endpoints" pattern.

~Currently untested.  Needs to be integrated into a test site, preferably both Gatsby v2 and v3.~

~Missing some utilities from v1:~
* ~`includePlugins` function, but there may be a better way to implement this.~
  
  ~`includePlugins` was a convenience function that allowed you to include plugins using strongly typed plugin options, and it also made the local-plugin transpiling process more explicit.  Local plugin transpiling is handled automatically within the context of the processed `gatsby-config` now; easier now that the proxy method isn't being used.~

* ~`GatsbyPluginDef` utility type for defining strongly typed plugin options~

---

### Remaining work

* [x] `includePlugins` utility function
* [x] Add `GatsbyPlugin` utility type
* [x] Testing
* [x] New docs

---

Closes #2 
Closes #18
Closes #20 
Closes #26 
Closes #27 
Closes #29

### CODE REVIEW

**Comment by dko-slapdash** [comment]
Hi @Js-Brecht, any plans on merging this PR?

**Comment by Js-Brecht** [comment]
Yeah, after it's tested.  I haven't had the time yet

**Comment by alvis** [comment]
Finally got some time to test this PR. 😓 

So far, I don't have any major problem with it.
It works as expected with Gatsby v3.

The only slightly annoying thing is the warning coming from webpack
```
[webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve '<path to my project>/gatsby-node.js' in '<path to my project>'
```

Somehow webpack wants to cache `gatsby-node.js` only instead of `gatsby-node.ts`.
Tried to trace the error down but can't find it. Any idea?

**Comment by Js-Brecht** [comment]
@alvis It seems strange to me that Webpack would care at all about `gatsby-node`, unless Gatsby has started hitting it with Webpack.. ??  Will have to look

**Comment by Js-Brecht** [comment]
Probably [this](https://github.com/gatsbyjs/gatsby/blob/4f9a724b91ce35b0232952023eaecb8db448719d/packages/gatsby/src/utils/webpack.config.js)... They're watching for changes to `gatsby-node` in order to invalidate the Webpack cache, which makes sense.

[Here's the docs](https://webpack.js.org/configuration/cache/#cachebuilddependencies) for `buildDependencies` in Webpack 5.  What I find interesting there is this:

> webpack will use a hash of each of these items and all dependencies to invalidate the filesystem cache.

"all dependencies" ... so is Webpack parsing the AST to look for imports and tracking them for changes, too?  If so, does it care if the modules are in Typescript?  May be something to test, because otherwise having `gatsby-node` in Typescript will break it.

I'm not sure if Webpack requires the extension on the module there, or if it will use its own resolution logic to look for the file once it needs to parse it.  If it uses its own resolution logic, then adding `.ts` to `resolve.extensions` would be sufficient, I'd think... otherwise,  I would probably try to do something like this:
```js
const resolveFile = (...fpath) => {
  try {
    return require.resolve(path.join(...fpath));
  } catch (err) {
    return "";
  }
}

...

    const cacheConfig = {
      type: `filesystem`,
      name: stage,
      cacheLocation,
      buildDependencies: {
        config: [
          __filename,
          ...store
            .getState()
            .flattenedPlugins.filter(plugin =>
              plugin.nodeAPIs.includes(`onCreateWebpackConfig`)
            )
            .map(plugin => resolveFile(plugin.resolve, `gatsby-node`))
            .filter(Boolean),
        ],
      },
    }
...
```

Using `require.resolve` at that point will use the extensions added by this plugin, so Node will pick up that there is `gatsby-node.ts`.  If the file doesn't exist, it will drop it from the array.

**Comment by alvis** [comment]
@Js-Brecht you nailed it. Yes. I tried to trace the error in the webpacke.config file and can confirm that the message is caused by that line.

The caching feature was implemented a few months ago here https://github.com/gatsbyjs/gatsby/pull/30857

**Comment by alvis** [comment]
Regrading `buildDependencies`, webpack doesn't consider it in the nodejs sense, but only takes it literally as paths of files that might change. So an explicit extension has to be given.

Your patch does exactly what we need to do to make the caching work again with `gatsby-config.ts`.

**Comment by Js-Brecht** [comment]
Thanks for opening that PR, @alvis.  I'm not certain yet if it's a blocker.  I could see there being issues if somebody has used `onCreateWebpackConfig`; if they change it later without clearing the cache, it could result in Webpack not picking up their changes.

I noticed a few other issues and did some house cleaning too.  Just need to get some docs written.  I think I'll be able to this week

**Comment by alvis** [comment]
Now you'd just receive a warning with caching disabled for gatsby-node. Probably it won't be harmful at all, but a fix has to be done sooner or later anyway. Thanks for finding the root cause. :)

**Comment by Js-Brecht** [comment]
Right, caching would be disabled for `gatsby-node`, but caching will still be enabled for [webpack.config.js](https://github.com/gatsbyjs/gatsby/blob/3651e932c507bb783e4385820a9ce1065843a908/packages/gatsby/src/utils/webpack.config.js#L804).  This means that `onCreateWebpackConfig` results will only be used once, so if changes are made to it in the default site's `gatsby-node`, it won't get picked up unless the cache is cleared.

This is probably something that won't happen frequently, and at least it spits out the warning; hopefully people will figure out from that they need to clear their cache if they're adding things to their webpack config.

I started to look at the `PackFileCacheStrategy` class yesterday too, but there's a lot to dig through in there.  I need to know if it follows a module's imports, because otherwise just adding `gatsby-node` may not be tracking changes anyway, if `onCreateWebpackConfig` is kept in a different module and simply exported from `gatsby-node`.  That doesn't relate to this plugin, though; it would be a core issue.

**Comment by roffelsaurus** [comment]
Looking forward to this!

**Comment by Js-Brecht** [comment]
To anybody watching this PR: I think I've got it to a point that I'm comfortable with.  I've released v2.0.0... 

Thanks a lot for your help and patience @alvis

**Pull request merged**
