### PR TITLE
Custom plugin resolver

### LINKED ISSUE #12: Handling custom plugins.
Hey,
I've figure it out that after using that plugin mine custom plugins are not discovered - even I've added also gatsby-config.js files to them.

```
 ERROR #10226  CONFIG

Couldn't find the "gatsby-plugin-fonts" plugin declared in "/path/to/project/node_modules/gatsby-plugin-ts-config/gatsby-config.js".

Tried looking for an installed package in the following paths:
 - /path/to/project/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-plugin-fonts
 - /path/to/project/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-plugin-fonts
 - /path/to/project/node_modules/gatsby/dist/node_modules/gatsby-plugin-fonts
 - /path/to/project/node_modules/gatsby/node_modules/gatsby-plugin-fonts
 - /path/to/project/node_modules/gatsby-plugin-fonts
 - /path/to/node_modules/gatsby-plugin-fonts
 - /Users/rroslaniec/node_modules/gatsby-plugin-fonts
 - /Users/node_modules/gatsby-plugin-fonts
 - /node_modules/gatsby-plugin-fonts
```
There is no lookup in /path/to/project/plugins folders (https://www.gatsbyjs.org/docs/creating-a-local-plugin/)

gatsby-plugin-fonts is our custom local plugin.

### PR DESCRIPTION
**Pull request by Js-Brecht**
This PR implements a new API: `includePlugins`.  With this function, you can resolve local/vendor plugins before they are given to Gatsby.  Resolving plugins this way will also transpile them, if they are Typescript, so that they are ready for consumption.

The type utility used for defining plugin option types, `IMergePluginOptions`, has been removed.  It is now replaced by `IGatsbyPluginDef`, which can be used in conjunction with `includePlugins`, to strongly type your plugin options.

The function export from `gatsby-node` and `gatsby-config` will no longer accept a second generic type parameter.

Use `includePlugins()` from now on to type your plugins.

---

Closes #12

### CODE REVIEW

**Comment by Js-Brecht** [comment]
Hey @Js-Brecht sorry for delay. Right now I got some time to test your solution. ALMOST works - right now normal plugins are not discoverable.

  **Error: [gatsby-plugin-ts-config] Unable to locate plugin gatsby-plugin-typescript**


gatsby-config.ts looks like this:

```ts
includePlugins([
 //local plugins
]);

const gatsbyConfig = {
  //some config
  plugins: [
    "gatsby-plugin-typescript",
    //and other
  ],
};

export default gatsbyConfig;

```

That do not depends on `gatsby-plugin-typescript` - whatever plugin you put at the first place will throw.

Also - I tried babel and ts-node compiler - same effect.

_Originally posted by @rroslaniec in https://github.com/Js-Brecht/gatsby-plugin-ts-config/issues/12#issuecomment-656177630_

**Comment by Js-Brecht** [comment]
@rroslaniec Hmm, that is odd.  It seemed to resolve plugins properly for me, so I wonder if it's because a difference in package manager or environment somewhere.  Do you mind sharing a reproduction so that I can track down where the issue is?

**Comment by Js-Brecht** [comment]
@rroslaniec I believe I've tracked the issue down.  It was an issue with the scoped require... my tests were done with yarn 2, and it handles that scoped require differently.  I forget sometimes that node's default `createRequire()` starts in the parent directory of the defined starting directory, so it winds up starting the search for a dependency one directory too high.

I've fixed it now, and published `gatsby-plugin-ts-config@next` as version `1.0.0-rc.4`, if you wouldn't mind testing it :pray:

**Comment by rroslaniec** [comment]
YES! Finally I tested it - and works perfectly! I'am very sorry about delay... :(

**Comment by Js-Brecht** [comment]
I'm glad to hear 🙂.  I will merge/publish this.  Sooner or later I hope to have the time to put into writing unit tests for this plugin 😆

**Comment by Js-Brecht** [comment]
Published in v1.0.0 🚀

**Pull request merged**
